### ISSUE TITLE
VPS Deployment?

### ISSUE THREAD

**Issue by shariq1989** [epicserve/django-base-site#287]
Just want to confirm that this starter is specifically for deployment to fly.io and not to a VPS.

**Comment by epicserve** [comment]
@shariq1989, thank you for the question. This starter can be used for any PaaS or VPS. I've used Heroku before, but stopped after they did away with the free plan. I'm sure it still works, but probably not without making some minor changes. I've used it with Fly.io before, see my [blog post](https://epicserve.com/django/2022/12/30/using-flyio-with-the-django-base-site.html) for more information.

I've also used it for for VPS setups, but it would probably take a little tweaking, because now a days I use [AppPack](https://apppack.io/) for work which is a self-hosted PaaS on AWS.

**Comment by shariq1989** [comment]
Thanks for sharing!
